### ISSUE TITLE
aboutFRN

### ISSUE THREAD

**Issue by xjyisok** [HuCaoFighting/HuCaoFighting.github.io#2]
HI
You say that The code about FRN can be found at the link (https://github.com/HuCaoFighting/FRN),but in fact there is nothing in this page. Can you upload the official implementation of the FRN。
Hope for your answer

**Comment by HuCaoFighting** [comment]
We have open sourced the codes. Please check it.

**Comment by xjyisok** [comment]
Thanks,the problem has been solved



---Original---
From: "Hu ***@***.***&gt;
Date: Fri, Nov 15, 2024 18:50 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [HuCaoFighting/HuCaoFighting.github.io] aboutFRN (Issue #2)




 
We have open sourced the codes. Please check it.
